version: "3.7"

services:

  mariadb:
    image: mariadb:10.4
    container_name: annonces-db
    ports:
      - 3306:3306
    volumes:
      - annonces-db-vol:/var/lib/mysql:z
    environment:
      - MYSQL_ROOT_PASSWORD=mariadb
    restart: unless-stopped

  php-apache:
    image: webdevops/php-apache
    container_name: annonces-srv
    ports:
      - 8080:80
    volumes:
      - "./:/app:z"
    environment:
      - PHP_DISPLAY_ERRORS=On
      - WEB_DOCUMENT_ROOT=/app/public
    depends_on:
      - mariadb
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: annonces-pma
    ports:
      - 8081:80
    volumes:
      - annonces-pma-vol:/var/lib/mysql:z
    environment:
      - MYSQL_ROOT_PASSWORD=mariadb
    depends_on:
      - mariadb
    restart: unless-stopped


volumes:
  annonces-db-vol:
  annonces-pma-vol:
